version: '3.3'

services:

  mysql-user:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: raf-si
      MYSQL_DATABASE: user
    ports:
      - "3306:3306"
    volumes:
      - mysql-user:/var/lib/mysql

volumes:
  mysql-user:
